version: '3.8'
services:
  flask:
    build: .
    container_name: OpenCV              
    restart: on-failure
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: python main.py